pipeline {
//   agent { label 'linux'}
  agent any

  tools {
    terraform 'Terraform'
    git 'Default'
  }
  // options {
  //   skipDefaultCheckout(true)
  // }
  stages{
    stage('clean workspace') {
      steps {
        cleanWs()
      }
    }
    stage('checkout') {
      steps {
        checkout scm
      }
    }

    // stage('tfsec') {
    //   // agent {
    //   //   docker { 
    //   //     image 'tfsec/tfsec-ci:v0.57.1' 
    //   //     reuseNode true
    //   //   }
    //   // }
    //   steps {
    //     dir ('Terraform/tfscan'){
    //       sh '''
    //         docker run --rm -it -v "$(pwd):/src" aquasec/tfsec  /src --no-color
    //       '''
    //     }
    //   }
    // }

    stage('terraform') {
      steps {
        dir('Terraform/tfscan'){
            sh 'terraform init'
            sh 'terraform apply -auto-approve -no-color'
        }
      }
    }
  }
  // post {
  //   always {
  //     cleanWs()
  //   }
  // }
}