name: Add Ingress Manifests to States Files

on:
  workflow_dispatch:
    inputs:
      cluster_name:
        type: choice
        required: true
        description: Select Cluster
        default: 'dev' 
        options: 
        - bronze
        - dev
        - iron
        - jade
        - lead
        - onyx
      namespace:
        type: string
        required: true
        description: Namespace
      ingress_name:
        type: string
        required: true
        description: Ingress Name
      service_name:
        type: string
        required: true
        description: Service Name
      port:
        type: string
        required: true
        description: Port Number
      host:
        type: string
        required: true
        description: Host URL

env:
  ## Sets environment variable for internet access
  http_proxy: http://azpse.astrazeneca.net:9480
  https_proxy: http://azpse.astrazeneca.net:9480
  no_proxy: 10.0.0.0/8,172.29.0.0/8,astrazeneca.net
  branch_name: "AZK-ingress-${{ inputs.cluster_name }}-${{ inputs.namespace }}-${{ github.run_number }}"

jobs:
  add-ingress-state-file:
    runs-on:
      - self-hosted
      - azimuth-azimuth-profiles
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Set APT Proxy Configuration
        run: |
          echo "Acquire::http::proxy \"${{ env.http_proxy }}\";" | sudo tee -a /etc/apt/apt.conf
          echo "Acquire::https::proxy \"${{ env.https_proxy }}\";" | sudo tee -a /etc/apt/apt.conf
          echo "Acquire::ftp::proxy \"${{ env.http_proxy }}\";" | sudo tee -a /etc/apt/apt.conf
          echo "Acquire::http::proxy::no_proxy \"${{ env.no_proxy }}\";" | sudo tee -a /etc/apt/apt.conf

      - name: Install wget
        run: |
          sudo apt-get update -y
          sudo apt-get install wget jq -y

      - name: Install GH Cli
        id: github-cli
        run: |
          mkdir -p .bin
          wget -q https://repo.azaibench.com/deploy/github/gh -O .bin/gh
          chmod +x .bin/gh
          echo "$GITHUB_WORKSPACE/.bin" >> $GITHUB_PATH

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install jinja2 argparse PyYAML==6.0.1

      - name: Add Ingress Manifest to State File
        run: |
          python generate_ingress_manifest.py -c ${{ inputs.cluster_name }} -a ${{ inputs.namespace }} -n ${{ inputs.ingress_name }} -s ${{ inputs.service_name }} -p ${{ inputs.port }} -r ${{ inputs.host }}
        working-directory: ./scripts
        env:
          KUBECONFIG: /tmp/kubeconfig

      - name: Git configure
        id: branch
        run: |
          git config --global user.email "kwsh888@astrazeneca.net"
          git config --global user.name "kwsh888_azu"
          git remote set-url --push origin https://kwsh888_azu:$GITHUB_TOKEN@github.com/azu-ignite/azimuth-profiles
          git checkout -b ${{ env.branch_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git Push and Raise-PR
        id: raise-pr
        run: |
          change_file=`git status --porcelain | grep -q . && echo true || echo false`
          if [[ "$change_file" == "true" ]]; then
            git add states/${{ inputs.cluster_name }}/.
            git commit -m "Adding ingress manifest to ${{ inputs.cluster_name }}/${{ inputs.namespace }} states file"
            git push --set-upstream origin ${{ env.branch_name }}
            gh pr create --title "Adding ingress manifest to ${{ inputs.cluster_name }}/${{ inputs.namespace }} states file" --body "Adding ingress manifest to ${{ inputs.cluster_name }}/${{ inputs.namespace }} states file" --base main --repo https://github.com/AZU-IGNITE/azimuth-profiles
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
