apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
 name: allow-all
 namespace: red
spec:
 rules:
 - {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-milvus-etcd
  namespace: brown-dev-001
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: etcd
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["brown-dev-001"]