# This is a sample to deploy a milvus cluster in milvus-operator's default configurations.
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: milvus-raghib
  labels:
    app: milvus
spec:
  mode: cluster
  # annotations:
  #   sidecar.istio.io/inject: "false"
  dependencies:
    storage:
      external: true
      type: S3
      endpoint: s3.eu-west-1.amazonaws.com
      secretRef: "mlpipeline-minio-artifact"
    etcd:
      inCluster:
        values:
          replicaCount: 1
          image:
            registry: harbor.csis.astrazeneca.net
            repository: milvusdb/etcd
            tag: 3.5.5-r4
        deletionPolicy: Delete
        pvcDeletion: true
    pulsar:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          images:
            zookeeper:
              repository: harbor.csis.astrazeneca.net/apachepulsar/pulsar
              # tag: 2.7.4
              pullPolicy: IfNotPresent
            bookie:
              repository: harbor.csis.astrazeneca.net/apachepulsar/pulsar
              # tag: 2.7.4
              pullPolicy: IfNotPresent
            autorecovery:
              repository: harbor.csis.astrazeneca.net/apachepulsar/pulsar
              # tag: 2.7.4
              pullPolicy: IfNotPresent
            broker:
              repository: harbor.csis.astrazeneca.net/apachepulsar/pulsar
              # tag: 2.7.4
              pullPolicy: IfNotPresent
            proxy:
              repository: harbor.csis.astrazeneca.net/apachepulsar/pulsar
              # tag: 2.7.4
              pullPolicy: IfNotPresent
            pulsar_manager:
              repository: harbor.csis.astrazeneca.net/apachepulsar/pulsar
              # tag: v0.1.0
              pullPolicy: IfNotPresent
              hasCommand: false
          monitoring:
            prometheus: false
            grafana: false
            node_exporter: false
            alert_manager: false
          components:
            autorecovery: false
            bookkeeper: true
          pulsar_metadata:
            component: pulsar-init
            image:
              # the image used for running `pulsar-cluster-initialize` job
              repository: harbor.csis.astrazeneca.net/apachepulsar/pulsar
              # tag: 2.7.4
              # pullPolicy: IfNotPresent
            ## set an existing configuration store
            # configurationStore:
            # configurationStoreMetadataPrefix: ""
            # configurationStorePort: 218
          zookeeper:
            replicaCount: 1
            annotations:
              sidecar.istio.io/inject: "false"
            resources:
              requests:
                memory: 256Mi
                cpu: 0.1
          bookkeeper:
            annotations:
              sidecar.istio.io/inject: "false"
            replicaCount: 1
          broker:
            annotations:
              sidecar.istio.io/inject: "false"
            replicaCount: 1
            resources:
            requests:
              memory: 512Mi
              cpu: 0.2
          proxy:
            annotations:
              sidecar.istio.io/inject: "false"
            replicaCount: 1
            resources:
              requests:
                memory: 128Mi
                cpu: 0.2
  components:
    image: harbor.csis.astrazeneca.net/milvusdb/milvus:v2.1.0
  config:
    minio:
      bucketName: az-eu-azimuth-kfp-dev
      # config the prefix of the bucket milvus will use
      rootPath: milvus/milvus-raghib
      useSSL: true