# This is a sample to deploy a milvus cluster in milvus-operator's default configurations.
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: milvus-raghib
  labels:
    app: milvus
spec:
  mode: cluster
  dependencies:
    storage:
      external: true
      type: S3
      endpoint: s3.amazonaws.com:443
      secretRef: "mlpipeline-minio-artifact"
    etcd:
      inCluster:
        values:
          replicaCount: 1
          image:
            registry: harbor.csis.astrazeneca.net
            repository: milvusdb/etcd
            tag: 3.5.5-r4
        deletionPolicy: Delete
        pvcDeletion: true
    pulsar:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          images:
            zookeeper:
              repository: harbor.csis.astrazeneca.net/apachepulsar/pulsar
              # tag: 2.7.4
              pullPolicy: IfNotPresent
            bookie:
              repository: harbor.csis.astrazeneca.net/apachepulsar/pulsar
              # tag: 2.7.4
              pullPolicy: IfNotPresent
            autorecovery:
              repository: harbor.csis.astrazeneca.net/apachepulsar/pulsar
              # tag: 2.7.4
              pullPolicy: IfNotPresent
            broker:
              repository: harbor.csis.astrazeneca.net/apachepulsar/pulsar
              # tag: 2.7.4
              pullPolicy: IfNotPresent
            proxy:
              repository: harbor.csis.astrazeneca.net/apachepulsar/pulsar
              # tag: 2.7.4
              pullPolicy: IfNotPresent
            pulsar_manager:
              repository: harbor.csis.astrazeneca.net/apachepulsar/pulsar
              # tag: v0.1.0
              pullPolicy: IfNotPresent
              hasCommand: false
          monitoring:
            prometheus: false
            grafana: false
            node_exporter: false
            alert_manager: false
          components:
            autorecovery: false
            bookkeeper: false
          pulsar_metadata:
            component: pulsar-init
            image:
              # the image used for running `pulsar-cluster-initialize` job
              repository: harbor.csis.astrazeneca.net/apachepulsar/pulsar
              # tag: 2.7.4
              # pullPolicy: IfNotPresent
            ## set an existing configuration store
            # configurationStore:
            # configurationStoreMetadataPrefix: ""
            # configurationStorePort: 218
          zookeeper:
            replicaCount: 1
            resources:
              requests:
                memory: 256Mi
                cpu: 0.1
          bookkeeper:
            replicaCount: 1
          broker:
            replicaCount: 1
            resources:
            requests:
              memory: 512Mi
              cpu: 0.2
            configData:
              PULSAR_MEM: >
                -Xms128m -Xmx256m -XX:MaxDirectMemorySize=256m
              PULSAR_GC: >
                -XX:+UseG1GC
                -XX:MaxGCPauseMillis=10
                -Dio.netty.leakDetectionLevel=disabled
                -Dio.netty.recycler.linkCapacity=1024
                -XX:+ParallelRefProcEnabled
                -XX:+UnlockExperimentalVMOptions
                -XX:+DoEscapeAnalysis
                -XX:ParallelGCThreads=4
                -XX:ConcGCThreads=4
                -XX:G1NewSizePercent=50
                -XX:+DisableExplicitGC
                -XX:-ResizePLAB
                -XX:+ExitOnOutOfMemoryError
                -XX:+PerfDisableSharedMem
                ## Enable `autoSkipNonRecoverableData` since bookkeeper is running
                ## without persistence
              autoSkipNonRecoverableData: "false"
              managedLedgerDefaultEnsembleSize: "1"
              managedLedgerDefaultWriteQuorum: "1"
              managedLedgerDefaultAckQuorum: "1"
          proxy:
            replicaCount: 1
            resources:
              requests:
                memory: 128Mi
                cpu: 0.2
  components:
    image: harbor.csis.astrazeneca.net/milvusdb/milvus:v2.1.0
  config: {}