apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: milvus-raghib
  labels:
    app: milvus
spec:
  mode: cluster
  # annotations:
  #   sidecar.istio.io/inject: "false"
  dependencies:
    storage: {}
    etcd: {}
    msgStreamType: "kafka"
    kafka:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          defaultReplicationFactor: 1
          offsetsTopicReplicationFactor: 1
          image:
            registry: harbor.csis.astrazeneca.net
            repository: bitnami/kafka
          replicaCount: 1
          zookeeper:
            replicaCount: 1
  components: {}
  config: {}