apiVersion: v1
kind: Pod
metadata:
  annotations:
    actions-runner-controller/token-expires-at: '2025-02-10T16:37:33+05:30'
    actions-runner/id: '2312'
    cni.projectcalico.org/containerID: 18f5d0973d8afec500e64125516e20d3165a3d42c4a563000f07cd10d978fd08
    cni.projectcalico.org/podIP: 172.29.20.5/32
    cni.projectcalico.org/podIPs: 172.29.20.5/32
    sidecar.istio.io/inject: 'false'
    sync-time: '2025-02-10T10:21:38Z'
  creationTimestamp: '2025-02-10T10:21:38Z'
  finalizers:
    - actions.summerwind.dev/runner-pod
  labels:
    actions-runner: ''
    actions-runner-controller/inject-registration-token: 'true'
    pod-template-hash: 5c8c95cb6
    runner-deployment-name: runner-deploy-azu-ignite-azimuth-profiles
    runner-template-hash: 5b84488ccb
  name: runner-deploy-azu-ignite-azimuth-profiles-dv2jk-j5g9j
  namespace: brown-dev-001
  ownerReferences:
    - apiVersion: actions.summerwind.dev/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Runner
      name: runner-deploy-azu-ignite-azimuth-profiles-dv2jk-j5g9j
      uid: 453791eb-7bf5-4d67-842e-512a866a2f13
  resourceVersion: '2576948377'
  uid: b272cdd7-39a1-4e60-9e0b-0a79eb8582a6
spec:
  containers:
    - env:
        - name: http_proxy
          value: 'http://azpse.astrazeneca.net:9480'
        - name: https_proxy
          value: 'http://azpse.astrazeneca.net:9480'
        - name: no_proxy
          value: '10.0.0.0/8,172.29.0.0/8,astrazeneca.net'
        - name: DISABLE_RUNNER_UPDATE
          value: 'true'
        - name: RUNNER_ORG
        - name: RUNNER_REPO
          value: azu-ignite/azimuth-profiles
        - name: RUNNER_ENTERPRISE
        - name: RUNNER_LABELS
          value: azimuth-azimuth-profiles
        - name: RUNNER_GROUP
        - name: DOCKER_ENABLED
          value: 'true'
        - name: DOCKERD_IN_RUNNER
          value: 'false'
        - name: GITHUB_URL
          value: 'https://github.com/'
        - name: RUNNER_WORKDIR
          value: /runner/_work
        - name: RUNNER_EPHEMERAL
          value: 'true'
        - name: RUNNER_STATUS_UPDATE_HOOK
          value: 'false'
        - name: GITHUB_ACTIONS_RUNNER_EXTRA_USER_AGENT
          value: actions-runner-controller/v0.27.6
        - name: DOCKER_HOST
          value: 'unix:///run/docker.sock'
        - name: RUNNER_NAME
          value: runner-deploy-azu-ignite-azimuth-profiles-dv2jk-j5g9j
        - name: RUNNER_TOKEN
          value: BCZY3JGDLE4VSPZNUSDW3LTHVHO7K
      image: >-
        harbor.csis.astrazeneca.net/summerwind/actions-runner:v2.321.0-ubuntu-22.04
      imagePullPolicy: Always
      name: runner
      resources:
        limits:
          cpu: '1'
          memory: 3Gi
        requests:
          cpu: '1'
          memory: 3Gi
      securityContext: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /runner
          name: runner
        - mountPath: /runner/_work
          name: work
        - mountPath: /run
          name: var-run
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-mdtrl
          readOnly: true
    - args:
        - dockerd
        - '--host=unix:///run/docker.sock'
        - '--group=$(DOCKER_GROUP_GID)'
      env:
        - name: http_proxy
          value: 'http://azpse.astrazeneca.net:9480'
        - name: https_proxy
          value: 'http://azpse.astrazeneca.net:9480'
        - name: no_proxy
          value: '10.0.0.0/8,172.29.0.0/8,astrazeneca.net'
        - name: DOCKER_GROUP_GID
          value: '121'
      image: 'harbor.csis.astrazeneca.net/docker/nvdia-dind:latest'
      imagePullPolicy: Always
      lifecycle:
        preStop:
          exec:
            command:
              - /bin/sh
              - '-c'
              - >-
                timeout "${RUNNER_GRACEFUL_STOP_TIMEOUT:-15}" /bin/sh -c "echo
                'Prestop hook started'; while [ -f /runner/.runner ]; do sleep
                1; done; echo 'Waiting for dockerd to start'; while ! pgrep -x
                dockerd; do sleep 1; done; echo 'Prestop hook stopped'"
                >/proc/1/fd/1 2>&1
      name: docker
      resources:
        limits:
          cpu: 200m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 512Mi
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /runner
          name: runner
        - mountPath: /run
          name: var-run
        - mountPath: /runner/_work
          name: work
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-mdtrl
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-10-201-11-38.emea.astrazeneca.net
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - emptyDir: {}
      name: runner
    - emptyDir: {}
      name: work
    - emptyDir:
        medium: Memory
        sizeLimit: 1M
      name: var-run
    - name: kube-api-access-mdtrl
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: '2025-02-10T10:24:50Z'
      status: 'True'
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: '2025-02-10T10:26:35Z'
      status: 'True'
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: '2025-02-10T10:26:35Z'
      status: 'True'
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: '2025-02-10T10:24:50Z'
      status: 'True'
      type: PodScheduled
  containerStatuses:
    - containerID: >-
        containerd://015fef0f9e79383c15bb412420218036124e787b3bfb9ff6d754b8fbb489ae1b
      image: 'harbor.csis.astrazeneca.net/docker/nvdia-dind:latest'
      imageID: >-
        harbor.csis.astrazeneca.net/docker/nvdia-dind@sha256:728bdff8a89c9f79c732b76bc10f5a58d73fc5114e5529b9d92d0922661d44ae
      lastState: {}
      name: docker
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: '2025-02-10T10:26:34Z'
    - containerID: >-
        containerd://39f023e0986f51d95a910a4387e5504386625425d70346e9e49207a45ccd61cf
      image: >-
        harbor.csis.astrazeneca.net/summerwind/actions-runner:v2.321.0-ubuntu-22.04
      imageID: >-
        harbor.csis.astrazeneca.net/summerwind/actions-runner@sha256:f04d689ed5b4ed3f56b0ff8428ce25f98b70e7c0c6900335e27b64cd46c71ad2
      lastState: {}
      name: runner
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: '2025-02-10T10:25:34Z'
  hostIP: 10.201.11.38
  phase: Running
  podIP: 172.29.20.5
  podIPs:
    - ip: 172.29.20.5
  qosClass: Burstable
  startTime: '2025-02-10T10:24:50Z'
