env.DnsServer = '16053-d1prdaddc.mwe.local'
env.DnsJumpServer = '16053-d1prdptg2.mwe.local'
env.SplunkDeploymentServer = 'splunklab.dev.paygateway.com:8089'
env.StaticSqlServer = 'mssql-listener-tools.dev.paygateway.com'
env.RemoveStorageLocations = "@(C:\\hyperVStorage)"
env.RemoveClusterFqdn = "@(ln-hyperv01.qa.paygateway.com)"
env.longDomain = 'dev.paygateway.com'
env.vLanId = '879'
env.virtualNetwork = 'SETSwitch'
env.IncludeTags = ''
env.ExcludeTags = ''
env.CustomArgument = ''
env.ParallelSlots = '6'
env.TestTypes = 'AcceptanceTests,ComponentTests'
env.BuildConfigurations = 'QAMock'
env.StandardWebDriverPoolSize = '6'
env.MobileWebDriverPoolSize = '6'
//env.chefRunList = "role[stack-full-dsc],role[logging-all],role[source-artifactory],recipe[mw::hosts_dev]" // Full Dsc Runlist
env.chefRunList = "role[stack-full-payments-dsc],role[logging-all],role[source-artifactory],recipe[mw::hosts_dev],recipe[iis-mw::encrypt_configs]" // PaymentsApi Dsc Runlist
//env.chefRunList = "role[stack-full],role[logging-all],role[source-artifactory],recipe[mw::hosts_dev]" // Minimal Dsc Runlist
//env.chefRunList = "role[stack-dns-server],role[stack-full],role[logging-all],role[source-artifactory],recipe[mw::hosts_dev]" // No DSC RunList
//env.DscList = "DnsServer,AppPreSetup,AppGateway,AppGwAdmin,AppPs1,AppBs1,AppManageMerchantware,AppManageCapitalBankcard,AppGenius,AppSso,AppTms,AppEcommerce,AppLogupload,AppTSys,AppTransport,AppHealth" // Full DSC List
//env.DscList = "DnsServer" // Minimal DSC List
env.DscList = "DnsServer,AppNewPreSetup,AppPayments,AppDecryption,AppTokenization,AppMerchantInfo" // PaymentsApi and AppTokenization List
env.AcceptInProgress = true
env.MigrationStrategies = 'Deploy'
env.DbEnvironment = 'Development'
env.ChefEnvironment = 'development'
env.AppParentName = 'cayan16_base-Dyn'
env.DbParentName = 'dbmocksnew16_base-Dyn'
env.TefParentName = 'cayan16_base-Dyn'
env.PerfMon = false
env.AutoStartDnsServer = true
env.KickoffTef = false
env.InfoLog = true
env.CommonBuildPattern = 'COMMON:1.0.20-Dev'
env.SnmpManagers = "@(10.100.20.140)"
env.SnmpDatacenter = 'DC1'
env.NessusServer = 'cloud.tenable.com:443'

//The only variable you will need to update from time to time due OS Template updates.
env.WindowsTemplateVersion = '9283.0'
env.LinuxTemplateVersion = '2310.0'
env.SophosVersion = '517'
env.OpenSshVersion = 'V8.6.0.0p1-Beta'
env.SecretServerUrl = 'https://secretserver.mi.local/SecretServer'
env.SecretServerDomain = 'intra.local'
env.Group = null
env.VmGeneration = '2'
env.CentOsSudoGroups = "%mwg_DevOpticard"
env.OUPath = 'OU=DTEs,OU=Servers,OU=OpenEdge,DC=dev,DC=paygateway,DC=com'
env.BuildPattern = null
env.AppHostName = null
env.DBHostName = null
env.TEFHostName = null
env.AppBaseVMName = null
env.DBBaseVMName = null
env.TEFBaseVMName = null

env.BaseWSDLEnvironment = 'HOT-BO3'
env.DataCenter = 'LN'
env.AllowedVMHosts = 'ln-hyperv02.dev.paygateway.com,ln-hyperv03.dev.paygateway.com,ln-hyperv04.dev.paygateway.com,ln-hyperv05.dev.paygateway.com,ln-hyperv06.dev.paygateway.com'
env.AllowedStorageLocations = 'C:\\ClusterStorage\\Volume1'
env.ClusterFqdn = null
env.IpAddress = null
env.SubnetMask = '22'
env.DefaultGateway = '10.249.92.1'
env.DnsServers = '10.249.202.21,10.249.202.22'
env.QaMasterServer= '10.248.204.21'
env.QaDnsName= 'qa.paygateway.com'