name: Generate CNPG DB Cluster

on:
  workflow_dispatch:
    inputs:
      cluster_name:
        type: choice
        required: true
        description: Select Cluster
        default: 'dev' 
        options: 
        - bronze
        - dev
        - iron
        - jade
        - lead
        - onyx
      namespace:
        description: Namespace
        type: string
        required: true
      pvc_storage_size:
        description: pvc storage size
        default: 100
        required: true
        type: number
      resource_memory:
        description: resource memory size (in Gi)
        type: string
        required: true
        default: "0.5"
      resource_cpu:
        description: resource cpu size
        type: string
        required: true
        default: "1"
      schedule_backup_time:
        description: Choose schedule Period
        type: choice
        required: true
        default: Weekly
        options:
        - Daily
        - Weekly
        - Monthly
      cnpg-ui-user:
        description: cnpg ui user
        type: string
        required: true
        default: "kwsh888@techvio.net"

env:
  ## Sets environment variable for internet access
  http_proxy: http://azpse.techvio.net:9480
  https_proxy: http://azpse.techvio.net:9480
  no_proxy: 10.0.0.0/8,172.29.0.0/8,techvio.net
  BRANCH_NAME: "cnpg-${{ inputs.cluster_name }}-${{ inputs.namespace }}-${{ github.run_number }}"

jobs:
  generate-cnpg-cluster:
    runs-on:
      - self-hosted
      - raghib-raghib-profiles
    env:
      ## Sets snvironment variable for cnpg cluster
      AWS_REGION: "eu-west-1"
      IMAGE_VERSION: "16.4"
      PGADMIN_IMAGE_VERSION: "8.14.0"
      NUMBER_INSTANCE: 3
      MEMORY: ${{ inputs.resource_memory }}
      CPU: ${{ inputs.resource_cpu }}

    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Set APT Proxy Configuration
        run: |
          echo "Acquire::http::proxy \"${{ env.http_proxy }}\";" | sudo tee -a /etc/apt/apt.conf
          echo "Acquire::https::proxy \"${{ env.https_proxy }}\";" | sudo tee -a /etc/apt/apt.conf
          echo "Acquire::ftp::proxy \"${{ env.http_proxy }}\";" | sudo tee -a /etc/apt/apt.conf
          echo "Acquire::http::proxy::no_proxy \"${{ env.no_proxy }}\";" | sudo tee -a /etc/apt/apt.con

      - name: Install wget
        run: |
          sudo apt-get update -y
          sudo apt-get install wget jq -y

      - name: Install GH Cli
        id: github-cli
        run: |
          mkdir -p .bin
          wget -q https://repo.azaibench.com/deploy/github/gh -O .bin/gh
          chmod +x .bin/gh
          echo "$GITHUB_WORKSPACE/.bin" >> $GITHUB_PATH

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r cnpg_module.txt
        working-directory: ./scripts

      - name: Create directory if not exist
        id: create-cluster-directory
        run: |
          mkdir -p cnpg-db/${{ inputs.cluster_name }}

      - name: Generate cnpg cluster Manifest
        id: manifest_file
        run: python generate_cnpg_manifest.py
        env:
          NAMESPACE: ${{ inputs.namespace }}
          CLUSTER: ${{ inputs.cluster_name }}
          PVC_STORAGE_SIZE: ${{ inputs.pvc_storage_size }}
          VAULT_USERNAME: ${{ secrets.VAULT_USERNAME }}
          VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
          SCHEDULEBACK_TIME: ${{ inputs.schedule_backup_time}}
          PGADMIN_USER: ${{ inputs.cnpg-ui-user}}
        working-directory: ./scripts
      
      - name: Modify Kustomization.yaml file
        run: |
          KUSTOMIZATION_FILE="kustomization.yaml"
          NEW_FILE_NAME="$NAMESPACE.yaml"

          # Check availabilty of kustomization.yaml file
          echo "Verifying is kustomization.yaml is present or not"
          if [[ -f $KUSTOMIZATION_FILE ]]; then
              echo "kutomization.yaml file is available"
          else
              echo "kutomization.yaml file not exist"
              echo -e "apiVersion: kustomize.config.k8s.io/v1beta1\nkind: Kustomization\n \nresources: " > "$KUSTOMIZATION_FILE"
              echo "Created kutomization.yaml file successfully!!!"
          fi
          echo "Editing kutomization.yaml file"
          sed -i "/^resources:/a\  - $NEW_FILE_NAME" $KUSTOMIZATION_FILE
        working-directory: ./cnpg-db/${{ env.CLUSTER }}/
        env:
          NAMESPACE: ${{ inputs.namespace }}
          CLUSTER: ${{ inputs.cluster_name }}

      - name: Git push changes to branch
        id: branch
        run: |
          git config --global user.email "kwsh888@techvio.net"
          git config --global user.name "kwsh888_azu"
          git remote set-url --push origin https://kwsh888_azu:$GITHUB_TOKEN@github.com/azu-ignite/raghib-profiles
          git checkout -b ${{ env.BRANCH_NAME }}
          git add cnpg-db/${{ inputs.cluster_name }}/.
          git commit -m "Adding cnpg cluster and schedulebackup manifest file: cnpg-db/${{ inputs.cluster_name }}/"
          git push --set-upstream origin ${{ env.BRANCH_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Raise-PR
        id: raise-pr
        run: |
          gh pr create --title "Adding cnpg manifest file: cnpg-db/${{ inputs.cluster_name }}/${{ inputs.namespace }}.yaml" --body "Adding cnpg manifest file: cnpg-db/${{ inputs.cluster_name }}/${{ inputs.namespace }}.yaml" --base main --repo https://github.com/AZU-IGNITE/raghib-profiles
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
