apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: production-rabbitmqcluster
spec:
  replicas: 3
  image: harbor.csis.astrazeneca.net/docker.io/library/rabbitmq:3.13.7-management
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  rabbitmq:
          additionalConfig: |
                  log.console.level = info
                  channel_max = 700
                  default_user= guest 
                  default_pass = guest
                  default_user_tags.administrator = true
  service:
    type: ClusterIP