pipeline {

    agent any

    stages {
        // stage ('Clean SCM'){
        //     steps {
        //         cleanWs()
        //     }
        // }

        stage('sourcecode checkout') {
            steps {
                script{

                    if ("${env.BRANCH_NAME}" == 'master'){
                        wrap([$class: 'BuildUser']) {
                            JOB_STARTED_BY = sh ( script: 'echo "${BUILD_USER}"', returnStdout: true).trim()          

                            echo "Pipeline was triggered by: ${JOB_STARTED_BY}"

                            if ("${JOB_STARTED_BY}" == ''){
                                sourceCodeCheckout this
                            } else {
                                println "This stage is skipped as a result of job/pipeline was manually triggered"
                            }
                        }
                    } else {
                        sourceCodeCheckout this
                    }
                }   
            }
        }
    }
}