apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  # namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: irsa-sa  # Service Account linked to IAM Role
      containers:
        - name: my-app
          image: amazon/awscli:latest
          command: 
            - sleep
            - "3600"
        
