pipeline {
//   agent { label 'linux'}
  agent any
  options {
    skipDefaultCheckout(true)
  }
  stages{
    stage('clean workspace') {
      steps {
        cleanWs()
      }
    }
    stage('checkout') {
      steps {
        checkout scm
      }
    }
    stage('terraform') {
      steps {
        dir('terrascan'){
            sh './terraformw apply -auto-approve -no-color'
        }
      }
    }
  }
  post {
    always {
      cleanWs()
    }
  }
}