pipeline {
//   agent { label 'linux'}
  agent any

  tools {
    terraform 'Terraform'
  }
  options {
    skipDefaultCheckout(true)
  }
  stages{
    stage('clean workspace') {
      steps {
        cleanWs()
      }
    }
    stage('checkout') {
      steps {
        checkout scm
      }
    }
    stage('terraform') {
      steps {
        dir('terrascan'){
            sh 'terraform init'
            sh 'terraform apply -auto-approve -no-color'
        }
      }
    }
  }
  post {
    always {
      cleanWs()
    }
  }
}