# Default values for rabbitmq-sample.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: raghib1992/raabitmq-sample-app
  tag: v1
  pullPolicy: Always